---
title: "Untitled"
author: 'Jiaxiang Miao '
date: "2020/12/17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
ji_xiao_biao <- read.csv(file="C:/Users/jiachunguang/Desktop/HR_comma_sep.csv", header=TRUE, sep=",")
str(ji_xiao_biao)  
summary(ji_xiao_biao)
library(corrplot)
corrplot(
  cor(ji_xiao_biao[, c(1:4,6:8)], use = "complete.obs"),
  method = "ellipse",
  is.corr = FALSE,
  diag = TRUE,
  tl.col = rgb(50, 50, 50, maxColorValue = 255)
)
level<-ji_xiao_biao$satisfaction_level
evaluation<-ji_xiao_biao$last_evaluation
montly<-ji_xiao_biao$average_montly_hours
project<-ji_xiao_biao$number_project
time<-ji_xiao_biao$time_spend_company
accident<-ji_xiao_biao$Work_accident
salary<-ji_xiao_biao$salary
left<-ji_xiao_biao$left
promotion<-ji_xiao_biao$promotion_last_5years
level_f<-cut(level,
             breaks = c(0,0.6,0.85,1),
             labels = c("3rd","2nd","1st"),
             include.lowest = TRUE, 
             ordered_result = TRUE)
level_f
as.data.frame(level_f)
level_f[1] > level_f[2]
evaluation_f<-cut(evaluation,
                  breaks = c(0,0.5,0.7,0.85,1),
                  labels = c("bad","med","Good","excellent"),
                  include.lowest = TRUE, 
                  ordered_result = TRUE)
evaluation_f
table(evaluation_f)
evaluation_f[1] > evaluation_f[2]
montly_f<-cut(montly,
              breaks = c(90,190,250,320),
              labels = c("short","normal","long"),
              include.lowest = TRUE, 
              ordered_result = TRUE)
montly_f
table(montly_f)
montly_f[1] > montly_f[2]
project_f<-cut(project,
               breaks = c(1,3,5,7),
               labels = c("less","normal","more"),
               include.lowest = TRUE, 
               ordered_result = TRUE)
project_f
table(project_f)
project_f[1] > project_f[2]
time_f<-cut(time,
            breaks = c(1,4,7,10),
            labels = c("short","normal","long"),
            include.lowest = TRUE, 
            ordered_result = TRUE)
time_f
table(time_f)
time_f[1] > time_f[2]
ji_xiao_biao$satisfaction_level<-factor(level_f)
ji_xiao_biao$last_evaluation<-factor(evaluation_f)
ji_xiao_biao$average_montly_hours<-factor(montly_f)
ji_xiao_biao$number_project<-factor(project_f)
ji_xiao_biao$time_spend_company<-factor(time_f)
ji_xiao_biao$Work_accident<-factor(ji_xiao_biao$Work_accident)
ji_xiao_biao$left<-factor(ji_xiao_biao$left)
ji_xiao_biao$promotion_last_5years<-factor((ji_xiao_biao$promotion_last_5years))
ji_xiao<-ji_xiao_biao[c(1:4,6:8)]
# View(ji_xiao)
library(arules)
library(Hmisc)
ji_xiao_raw<-as.data.frame(ji_xiao)
str(ji_xiao_raw)
ji_xiao_trans <- as(ji_xiao_raw, "transactions")
irules_args_default <- apriori(ji_xiao_raw)
inspect(irules_args_default)
irules_args_default_in_df <- as(irules_args_default, "data.frame")
col1_without_braces <-gsub("[\\{\\}]", "", irules_args_default_in_df$rules)
left_and_right <-do.call("rbind", strsplit(col1_without_braces, split = " => "))
left_and_right <- as.data.frame(left_and_right)
names(left_and_right) <- c("LHS", "RHS")
irules_in_df <-cbind(left_and_right, irules_args_default_in_df[, -1])
```


```{r}
library(arules)
rules_left<-apriori(ji_xiao_raw[c(2:6)],
                    parameter = list(minlen=1,supp=0.005,conf=0.8),
                    appearance = list(rhs= paste0("left=",c("0","1")),
                                      default="lhs"))
rules_left_sorted <- sort(rules_left, by = "lift")
subset.matrix <-is.subset(rules_left_sorted, rules_left_sorted, sparse = FALSE)
subset.matrix[lower.tri(subset.matrix, diag = TRUE)] <- NA
redundant <- colSums(subset.matrix, na.rm = TRUE) >= 1
which(redundant)
rules_left_pruned <- rules_left_sorted[!redundant]
inspect(rules_left_pruned)
inspect(sort(rules_left_pruned,by="support")[1:6])
inspect(sort(rules_left_pruned,by="confidence")[1:6])
quality(rules_left) 
itemFrequency(ji_xiao_trans, type = "relative")
itemFrequencyPlot(ji_xiao_trans)
itemsets <- apriori(ji_xiao_raw,
                    parameter = list(minlen = 2,
                                     supp = 0.005,
                                     target = "frequent itemsets"))
inspect(itemsets)
itemsets <- unique(generatingItemsets(rules_left_pruned))
itemsets
inspect(itemsets)
library(arulesViz)
plot(rules_left_pruned, method = "graph")
plot(rules_left_pruned, method = "paracoord")
```

```{r}
rules_level<-apriori(ji_xiao_raw[,1:5],
                     parameter = list(minlen=1,supp=0.005,conf=0.8),
                     appearance = list(rhs=paste0("satisfaction_level=",c("1st","2nd","3rd")),
                                       default="lhs"))
rules_level_sorted <- sort(rules_level, by = "lift")
subset.matrix <-is.subset(rules_level_sorted, rules_level_sorted, sparse = FALSE)
subset.matrix[lower.tri(subset.matrix, diag = TRUE)] <- NA
redundant <- colSums(subset.matrix, na.rm = TRUE) >= 1
which(redundant)
rules_level_pruned <- rules_level_sorted[!redundant]
inspect(rules_level)
inspect(sort(rules_level,by="support")[1:6]) 
inspect(sort(rules_level,by="confidence")[1:6]) 
quality(rules_level)
itemsets <- unique(generatingItemsets(rules_level_pruned))
itemsets
inspect(itemsets)[1:5]
library(arulesViz)
plot(rules_level_pruned, method = "graph")
plot(rules_level_pruned, method = "paracoord")
```

```{r}
rules_promotion<-apriori(ji_xiao_raw[,c(2:5,7)],
                         parameter = list(minlen=1,supp=0.005,conf=0.8),
                         appearance = list(rhs=paste0("promotion_last_5years=",c("0","1")),
                                           default="lhs"))
rules_promotion_sorted <- sort(rules_promotion, by = "lift")
subset.matrix <-is.subset(rules_promotion_sorted, rules_promotion_sorted, sparse = FALSE)
subset.matrix[lower.tri(subset.matrix, diag = TRUE)] <- NA
redundant <- colSums(subset.matrix, na.rm = TRUE) >= 1
which(redundant)
rules_promotion_pruned <- rules_promotion_sorted[!redundant]
inspect(rules_promotion)
inspect(sort(rules_promotion,by="support")[1:6]) 
inspect(sort(rules_promotion,by="confidence")[1:6]) 
quality(rules_promotion)
itemsets <- unique(generatingItemsets(rules_promotion_pruned))
itemsets
inspect(itemsets)
library(arulesViz)
plot(rules_promotion_pruned, method = "graph")
plot(rules_promotion_pruned, method = "paracoord")
```

```{r}
library(randomForest)
importance_promotion<-randomForest(ji_xiao_biao[,8]~.,data=ji_xiao_biao[,c(2:4,6)],importance=TRUE,ntree=1000,type="class")
rfimp<-importance(x=importance_promotion)                                     
rfimp
varImpPlot(importance_promotion)      
```

